language: python
cache: pip
python:
    - "2.7"

install:
    - pip install -r requirements-dev.txt
    - pip install .

script:
    - flake8
    - py.test -v tests/

after_success: curl -X POST https://readthedocs.org/build/pynsot
